version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
